#spring:
#  application:
#    name: cloud-payment-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&&characterEncoding-utf-8&useSSL=false
#    username: root
#    password: 523422
#  zipkin:
#    base-url: http://192.168.188.128:9411
#  sleuth:
#    sampler:
#      probability: 1 #采样率介于 0 到 1 之间 ，1 表示全部采集